name: Release

on:
  push:
    branches: [ master-se212website ]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10.10'

      - run: npm install

      - run: npm run build

      - run: tar -czf ../Boole.tar.gz *
        working-directory: build/

      - run: echo "::set-output name=datetime::$(date +'%Y-%m-%dT%H-%M-%S')"
        id: datetime

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "Boole.tar.gz"
          tag: ${{ steps.datetime.outputs.datetime }}
          commit: "master-se212website"
          token: ${{ secrets.GITHUB_TOKEN }}
